### ISSUE TITLE
Request assertion does not take into account query args

### ISSUE THREAD

**Issue by alexcouper** [apibyexample/abe-python#17]
In https://github.com/apibyexample/abe-python/blob/master/abe/unittest.py#L128 `sample_request` looks like 

```
{u'url': u'/api/v3/events/', u'body': {}, u'queryParams': {u'foo': u'bar'}, 'method': u'GET'}
```

But the queryParams are not asserted to match against the JSON.

**Comment by txels** [comment]
Fixed in #18
